<a href="https://colab.research.google.com/github/sangameshks/SkillovillaTraining/blob/main/linear_algebra_and_probability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pre-requisites for this session:**

    1. Basic operations in python
    2. Data types in Python
    3. Numpy

# Topics for Today:

1. **Vectors**

      
2. **Metrices**


3. **Probability.**
      

# Linear Algebra

**Linear Algebra is a branch of mathematics that is extremely useful in data science and machine learning, it helps in the study of linear functions in vector spaces. Linear algebra is used in data preprocessing, data transformation, and model evaluation.**


**Linear algebra is used in many different areas of data science, such as:**

* **Data preprocessing**


* **Data visualization**


* **Machine learning**


* **Natural language processing**


* **Computer vision**

# Vectors and Metrices

**Vectors and matrices are the basic building blocks of linear algebra. They are used to represent data and to perform operations on data.**

**Vectors:**

   * **Vector is a mathematical object that has both magnitude and direction.**
   
   * **It can be represented as a list of numbers, where each number represents the magnitude of the vector in a particular direction.**
   * **For example, the vector (1, 2, 3) represents a vector that has a magnitude of 3 and is pointing in the direction (1, 2, 3).**
   

**Metrices:**

**A matrix is a rectangular array of numbers. It can be used to represent a system of linear equations, or to store data in a tabular format.**

**For example,**

[1 2 3]

[4 5 6]

[7 8 9]

### Creation of Vectors

**Python NumPy module is used to create a vector. We use numpy.array() method to create a one-dimensional array i.e. a vector.**

**Syntax:**
**numpy.array(list)**

**Demo**

**Question: How can a vector be created in Python using the list [10, 20, 30, 40, 50]?**

In [ ]:
# Example 1: Horizontal Vector
import numpy as np

lst = [10,20,30,40,50]

vct = np.array(lst)

print("Vector created from a list:")
print(vct)

Vector created from a list:
[10 20 30 40 50]


**Question: 2 Create a vertical vector from the list [10, 20, 30, 40, 50].**

In [ ]:
# Example 2: Vertical Vector

import numpy as np

lst = [[2],
        [4],
        [6],
          [10]]

vct = np.array(lst)

print("Vector created from a list:")
print(vct)

Vector created from a list:
[[ 2]
 [ 4]
 [ 6]
 [10]]


## Scalar, Vector and Matrices

![image-2.png](attachment:image-2.png)

In [ ]:
# creating a dataset
import numpy as np
import pandas as pd
df = pd.read_csv("C:/Users/DELL/Desktop/lab remake/m9/Untitled Folder/kc_house_data.csv")
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [ ]:
df.iloc[[0]]

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3        1.0         1180   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   

   sqft_lot15  
0        5650  

[1 rows x 21 columns]

#### **Scalar:**

**Scalars are basically just normal real numbers. We can think of them like any regular value we use. Any single value from our dataset would represent a scalar.**

**For example: In the dataset the number of bedrooms in our house price data, for example, would be a scalar. If we only used one feature as an input from our house price data, then we could represent that as a scalar value.**

In [ ]:
print(df['bedrooms'].values[0])

3


#### **Vectors:**

* **There are many factors that can affect the price of a house, such as the total square footage, the number of bedrooms and bathrooms, the location, and the condition of the house.**

* **To represent multiple features in house price data, we can use a vector. A vector is a 1-D data structure that can hold multiple values.**

* **For example, we could create a vector to represent the total square footage, the number of bedrooms, and the number of bathrooms of a house. This vector would have three elements, one for each feature. We can then pass this vector to a machine learning model to predict the price of the house.**

In [ ]:
# This is a numpy row vector
print(df[["bedrooms", "sqft_lot"]].values[:1])

[[   3 5650]]


#### **Matrices**

* **So far, we have only looked at the first house in our dataset. However, what if we need to pass in batches of multiple houses, with their bedroom and square foot/meter values? This is where matrices come in.**

* **A matrix is a 2-D data structure, where the two dimensions refer to the number of rows and columns.**

* **For example, if we have a dataset of 10 houses, we could represent each house as a row in a matrix. The columns of the matrix would represent the features of each house, such as the number of bedrooms, the square footage, and the price.**

* **Here is an example of how we could represent the features of 10 houses in a matrix:**

In [ ]:
print(df[["bedrooms", "sqft_lot"]].values[:2])

[[   3 5650]
 [   3 7242]]


**Demo**

In [ ]:
# Data

id =[0,1,2,3,4,5,6,7,8]
Sqft_living = [1500,2000,2500,3000,3500,4000,4500,5000,5500]
Bathroom =[3,4,5,6,7,8,9,10,11]
Bedroom = [2,3,4,5,6,7,8,9,10]
Price = [2,00,000,3,00,000,4,00,000,5,00,000,6,00,000,7,00,000,8,00,000,9,00,000,10,00,000]

#### **Question: 1**

**Create a scalar to access the element in the dataset that corresponds to the first record of the "bathroom" column.**

In [ ]:
price = Bathroom[0]
price

3

#### **Question :2**

**Create a Vector to access the elements in the dataset that correspond to the "sqft_living", "bathrooms", and "bedrooms" columns.**

In [ ]:
import numpy as np

# Create a list of the number of  Bathroom, Bedroom, square footage
house_features = [3,2,1500]

# Convert the list to a NumPy array
house_features_array = np.array(house_features)

# Print the list of house features
print(house_features_array)


[   3    2 1500]


**Question: 3**

**Given the following list of house features, create a matrix with four columns: bathrooms, bedrooms, square footage, and price. The matrix should have four rows, one for each house in the list.**

In [ ]:
import numpy as np

# Create a list of the number of  Bathroom, Bedroom, square footage
house_features = [3,2,1500,200000],[4,3,2000,300000],[5,4,2500,400000],[6,5,3000,500000]

# Convert the list to a NumPy array
house_features_array = np.array(house_features)

# Print the list of house features
print(house_features_array)

[[     3      2   1500 200000]
 [     4      3   2000 300000]
 [     5      4   2500 400000]
 [     6      5   3000 500000]]


### **Practice Time**

**Question: 1 Given a list of bedrooms consisting of 3 bedrooms, 2 bedrooms, and 1 bedroom, represent the number of bedrooms as a single number or in scalar format.**

In [ ]:
import numpy as np

# Create a list of the number of bedrooms in a house
bedrooms = [3, 2, 1]

# Convert the list to a NumPy array
bedrooms_array = np.array(bedrooms)

# Print the number of bedrooms in the first house
print(bedrooms_array[0])


3


**Question: 2**
**Given a list of bedroom consisting of 3 bedroom, 2 bathroom and square foot which is 1500, represent the number of bedroom, bathroom and sqaure foot as a vector.**

In [ ]:
import numpy as np

# Create a list of the number of bedrooms, bathrooms, and square footage of a house
house_features = [3, 2, 1500]

# Convert the list to a NumPy array
house_features_array = np.array(house_features)

# Print the list of house features
print(house_features_array)


[   3    2 1500]


**Question: 3**

**Python to represent the relationship between the number of bedrooms, bathrooms, and square footage of a house as a matrix:**

**Bathroom =[2,4,5]**

**Bedroom = [2,3,4]**

**Sqft_living = [1500,2000,2500]**

In [ ]:
import numpy as np

# Create a list of the number of bathrooms, bedroom and square footage of a house
house_features = [[2, 2, 1500], [4, 3, 2000], [5, 4, 2500]]

# Create a list of the prices of the houses

# Convert the lists to NumPy arrays
house_features_array = np.array(house_features)
#print(house_features_array)


# Create a matrix that represents the relationship between each of the house features.
house_features_matrix = (house_features_array)
# Print the house featurrs matrix
print(house_features_matrix)

[[   2    2 1500]
 [   4    3 2000]
 [   5    4 2500]]


### **Operations of Vectors and Matrices:**

**Vectors and matrices can be added, subtracted, multiplied, and divided. They can also be used to perform operations on data, such as finding the mean, median, and mode of a set of numbers.**

**Here are some of the common operations on vectors and matrices:**

* **Addition:** **Two vectors can be added by adding corresponding elements. For example, the vectors (1, 2, 3) and (4, 5, 6) can be added to get the vector (5, 7, 9).**


* **Subtraction:** **Two vectors can be subtracted by subtracting corresponding elements. For example, the vectors (1, 2, 3) and (4, 5, 6) and can be subtracted to get the vector (-3, -3, -3).**



* **Multiplication:** **A vector can be multiplied by a scalar by multiplying each element of the vector by the scalar. For example, the vector (1, 2, 3) can be multiplied by the scalar 2 to get the vector (2, 4, 6).**


* **Matrix multiplication:** **Two matrices can be multiplied by multiplying corresponding elements of each matrix. For example, the matrices.**

## **Basic Operations on a Python Vector:**

**Here is a list of the basic operations that can be performed on a Vector–**

* **Addition**

* **Subtraction**

* **Multiplication**

* **Division**

* **Dot Product**

**1. Performing addition operation on a Python Vector:**

**The addition operation would take place in an element-wise manner i.e. element by element and further the resultant vector would have the same length as of the two additive vectors.**

**Syntax:**

**vector + vector**

In [ ]:
import numpy as np

lst1 = [10,20,30,40,50]
lst2 = [1,2,3,4,5]


vctr1 = np.array(lst1)

vctr2= np.array(lst2)


print("Vector created from a list 1:")
print(vctr1)
print("Vector created from a list 2:")
print(vctr2)

vctr_add = vctr1+vctr2
print("Addition of two vectors: ",vctr_add)

Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[1 2 3 4 5]
Addition of two vectors:  [11 22 33 44 55]


**2. Performing Subtraction of two vectors:**

**In subtraction, the elements of vector 2 will be subtracted from the corresponding elements of vector 1, one at a time.**

In [ ]:
import numpy as np

lst1 = [10,20,30,40,50]
lst2 = [1,2,3,4,5]

vctr1 = np.array(lst1)

vctr2= np.array(lst2)

print("Vector created from a list 1:")
print(vctr1)
print("Vector created from a list 2:")
print(vctr2)

vctr_sub = vctr1-vctr2
print("Subtraction of two vectors: ",vctr_sub)

Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[1 2 3 4 5]
Subtraction of two vectors:  [ 9 18 27 36 45]


**3. Performing multiplication of two vectors:**

**In vector multiplication, the corresponding elements of two vectors are multiplied together, and the resulting vector has the same length as the original vectors.**

**Let us try to visualize the multiplication operation:**

x = [10,20] and y = [1,2] are two vectors. So the product vector would be v[ ],

v[0] = x[0] * y[0]
v[1] = x[1] * y[1]

In [ ]:
import numpy as np

lst1 = [10,20,30,40,50]
lst2 = [1,2,3,4,5]

vctr1 = np.array(lst1)

vctr2= np.array(lst2)

print("Vector created from a list 1:")
print(vctr1)
print("Vector created from a list 2:")
print(vctr2)

vctr_mul = vctr1*vctr2
print("Multiplication of two vectors: ",vctr_mul)

Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[1 2 3 4 5]
Multiplication of two vectors:  [ 10  40  90 160 250]


**4. Performing Vector division operation:**

**In vector division, the resultant vector is the quotient values after carrying out division operation on the two vectors.**

**For example:**

x = [10,20] and y = [1,2] are two vectors. So the resultant vector v would be,

v[0] = x[0] / y[0]

v[1] = x[1] / y[1]

In [ ]:
import numpy as np

lst1 = [10,20,30,40,50]
lst2 = [10,20,30,40,50]

vctr1 = np.array(lst1)

vctr2= np.array(lst2)

print("Vector created from a list 1:")
print(vctr1)
print("Vector created from a list 2:")
print(vctr2)

vctr_div = vctr1/vctr2
print("Division of two vectors: ",vctr_div)

Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[10 20 30 40 50]
Division of two vectors:  [1. 1. 1. 1. 1.]


**Practice Time:**

**Question:**

**Marks of students in different subjects out of 50:**

**Roll no = [1,2,3,4,5,6,7,8,9,10]**

**English = [35,45,34,47,36,39,41,30,44,29]**
          
**Maths = [40,31,42,46,28,30,35,39,34,41]**
         
**Biology = [29,33,45,27,43,31,34,32,42,30]**
            
**Physics = [35,45,34,47,36,39,41,30,44,29]**
           
**Chemistry = [40,31,42,46,28,30,35,39,34,41]**  
            
**Total Negative marking = [7,8,0,3,5,12,0,2,1,7]**


**Answer the following:**

* **Q.1 Determine the sum of the marks obtained by students in each subject.**

* **Q.2 Deduct the negative marking from the students' total marks and calculate their final score.**

* **Q.3 Calculate the students' marks out of 100, given that their original marks were out of 50.**

* **Q.4 Find the avarage mark scored by each students in all subjects.**

In [ ]:
#Answer: 1

import numpy as np

Roll_no = [1,2,3,4,5,6,7,8,9,10]
English = np.array([35, 45, 34, 47, 36, 39, 41, 30, 44, 29])
Maths = np.array([40, 31, 42, 46, 28, 30, 35, 39, 34, 41])
Biology = np.array([29, 33, 45, 27, 43, 31, 34, 32, 42, 30])
Physics = np.array([35, 45, 34, 47, 36, 39, 41, 30, 44, 29])
Chemistry = np.array([40, 31, 42, 46, 28, 30, 35, 39, 34, 41])

# Add the vectors
total_marks = English + Maths + Biology + Physics + Chemistry

# Print the total marks
print(Roll_no)
print(total_marks)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[179 185 197 213 171 169 186 170 198 170]


In [ ]:
# Answer:2
Roll_no = [1,2,3,4,5,6,7,8,9,10]
English = np.array([35, 45, 34, 47, 36, 39, 41, 30, 44, 29])
Maths = np.array([40, 31, 42, 46, 28, 30, 35, 39, 34, 41])
Biology = np.array([29, 33, 45, 27, 43, 31, 34, 32, 42, 30])
Physics = np.array([35, 45, 34, 47, 36, 39, 41, 30, 44, 29])
Chemistry = np.array([40, 31, 42, 46, 28, 30, 35, 39, 34, 41])

Total_Negative_marking = [7,8,0,3,5,12,0,2,1,7]


# Add the vectors
total_marks = English + Maths + Biology + Physics + Chemistry

# Print the total marks
print(Roll_no)
print(total_marks)

#deducting negative markings on total marks

negative_marks=total_marks-Total_Negative_marking
print(Roll_no)
print(negative_marks)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[179 185 197 213 171 169 186 170 198 170]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[172 177 197 210 166 157 186 168 197 163]


In [ ]:
#Answer:3

Roll_number = ['Student 1', 'Student 2', 'Student 3', 'Student 4', 'Student 5', 'Student 6', 'Student 7', 'Student 8', 'Student 9', 'Student 10']

Roll_no = [1,2,3,4,5,6,7,8,9,10]
English = np.array([35, 45, 34, 47, 36, 39, 41, 30, 44, 29])
Maths = np.array([40, 31, 42, 46, 28, 30, 35, 39, 34, 41])
Biology = np.array([29, 33, 45, 27, 43, 31, 34, 32, 42, 30])
Physics = np.array([35, 45, 34, 47, 36, 39, 41, 30, 44, 29])
Chemistry = np.array([40, 31, 42, 46, 28, 30, 35, 39, 34, 41])


print("Marks out of 50")
print(English)
print(Maths)
print(Biology)
print(Physics)
print(Chemistry)
# coversion of 50 marks to 100

new_english = English*2
new_maths = Maths*2
new_bio = Biology*2
new_phy = Physics*2
new_chem = Chemistry*2



print("................................")
print("Marks out of 100")
print(Roll_no)
print(new_english)
print(new_maths)
print(new_bio)
print(new_phy)
print(new_chem)

Marks out of 50
[35 45 34 47 36 39 41 30 44 29]
[40 31 42 46 28 30 35 39 34 41]
[29 33 45 27 43 31 34 32 42 30]
[35 45 34 47 36 39 41 30 44 29]
[40 31 42 46 28 30 35 39 34 41]
................................
Marks out of 100
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[70 90 68 94 72 78 82 60 88 58]
[80 62 84 92 56 60 70 78 68 82]
[58 66 90 54 86 62 68 64 84 60]
[70 90 68 94 72 78 82 60 88 58]
[80 62 84 92 56 60 70 78 68 82]


In [ ]:
# Answer:4

import numpy as np

# Create a list of students
students = ['Student 1', 'Student 2', 'Student 3', 'Student 4', 'Student 5', 'Student 6', 'Student 7', 'Student 8', 'Student 9', 'Student 10']

# Create a list of subjects
subjects = ['English', 'Maths', 'Bio', 'Physics', 'Chemistry']

# Create a list of marks for each student in each subject
marks = np.array([
    [70, 80, 58, 70, 80],
    [90, 62, 66, 90, 62],
    [68, 84, 90, 54, 84],
    [94, 92, 54, 86, 92],
    [72, 56, 62, 62, 56],
    [78, 60, 68, 68, 60],
    [82, 70, 64, 64, 70],
    [60, 78, 84, 84, 68],
    [88, 68, 60, 60, 82],
    [58, 82, 60, 58, 82],
])

# Calculate the average mark for each student
average_marks = np.mean(marks, axis=1)

# Print the average marks for each student
for student, average_mark in zip(students, average_marks):
    print(f'{student}: {average_mark}')

Student 1: 71.6
Student 2: 74.0
Student 3: 76.0
Student 4: 83.6
Student 5: 61.6
Student 6: 66.8
Student 7: 70.0
Student 8: 74.8
Student 9: 71.6
Student 10: 68.0


**Practice Time with Dot Product:**

In [ ]:
import numpy as np

lst1 = [10,20,30,40,50]
lst2 = [1,1,1,1,1]


vctr1 = np.array(lst1)

vctr2= np.array(lst2)


print("Vector created from a list 1:")
print(vctr1)
print("Vector created from a list 2:")
print(vctr2)

vctr_dot = vctr1.dot(vctr2)
print("Dot product of two vectors: ",vctr_dot)

Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[1 1 1 1 1]
Dot product of two vectors:  150


In [ ]:
#In Python 3.5 and later, you can also use the **@** operator to calculate the dot product:
import numpy as np

v = np.array([2,1])
s = np.array([-3,2])
d = v @ s
print (d)

-4


**5. Performing Vector operation in dot product:**

**In a vector dot product, we perform the summation of the product of the two vectors in an element-wise fashion.
 It can be calculated using the following formula:**

**vector c = x . y = (x1 * y1 + x2 * y2)**

**Demo**

**Question: Given two lists, lst1 having values comprising of [10,20,30,40,50] and lst2 consisting of [1,1,1,1,1], calculate the dot product of the vectors created from these lists.**

In [ ]:
#Dot Product

import numpy as np

lst1 = [10,20,30,40,50]
lst2 = [1,1,1,1,1]


vctr1 = np.array(lst1)

vctr2= np.array(lst2)


print("Vector created from a list 1:")
print(vctr1)
print("Vector created from a list 2:")
print(vctr2)

vctr_dot = vctr1.dot(vctr2)
print("Dot product of two vectors: ",vctr_dot)

Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[1 1 1 1 1]
Dot product of two vectors:  150


**Practice Time**

**Question: 1**

**Using the information provided in the below, what is the outcome of the dot product operation between the "cost_of_production" array and the "weights" array?**

 **1.  cost_of_production = [100, 200, 300]**

 **2.  weights = [0.2, 0.5, 0.3]**

In [ ]:
import numpy as np

# Define the cost of production and the weights
cost_of_production = np.array([100, 200, 300])
weights = np.array([0.2, 0.5, 0.3])

# Calculate the weighted average
weighted_average = np.dot(cost_of_production, weights)

# Print the result
print(weighted_average)

210.0


**Question: 2**

**Given below are the quantities bought by Nicole and their respective prices of the grocery items, what is the total amount by calculating the dot product of the "kilograms" array and the "price" array?**

**kilograms = [1, 2, 3]**

**price = [10, 20, 30]**

In [ ]:
import numpy as np

# Define the kilograms and price of each grocery item
kilograms = np.array([1, 2, 3])
price = np.array([10, 20, 30])

# Calculate the total amount
total_amount = np.dot(kilograms, price)

# Print the result
print(total_amount)

140


**Cross Product:**

* **The cross product in Python is a mathematical operation that takes two vectors and produces a third vector.**

* **The third vector is perpendicular to the plane that contains the first two vectors.**

* **The length of the third vector is equal to the area of the parallelogram formed by the first two vectors.**



**The cross product can be calculated using the following formula:**

**cross_product = (a2 * b3 - a3 * b2, a3 * b1 - a1 * b3, a1 * b2 - a2 * b1)**


In [ ]:
#finding the area of triangle using cross product

import numpy as np

# Define the vectors representing the sides of the triangle
a = np.array([2, 8, 12])
b = np.array([2, 6, 3])

# Calculate the area of the triangle
area = 0.5 * np.linalg.norm(np.cross(a, b))

# Print the result
print("Area of the triangle:", area)

Area of the triangle: 25.709920264364882


**Question: 1**

**Write a function that takes two vectors as input, a position vector and a force vector, and returns the torque vector. The torque vector is calculated using the cross product of the two vectors based on the values given below.**

**position = (1, 2, 3)**

**force = (4, 5, 6)**

In [ ]:
import numpy as np

# Calculate torque using cross product
def calculate_torque(position_vector, force_vector):
    torque = np.cross(position_vector, force_vector)
    return torque

# Example usage
position = np.array([1, 2, 3])
force = np.array([4, 5, 6])
torque_result = calculate_torque(position, force)
print("Torque:", torque_result)

Torque: [-3  6 -3]


**Question: 2**

**Given the sides of a triangle as vectors [0, 0], [4, 0], and [2, 3], what is the area of the triangle using cross product function?**

In [ ]:
import numpy as np

# Calculate area of triangle using cross product
def calculate_triangle_area(vertices):
    # Extract the vertices of the triangle
    v1, v2, v3 = vertices

    # Calculate two vectors within the triangle
    vector1 = v2 - v1
    vector2 = v3 - v1

    # Calculate the cross product
    cross_product = np.cross(vector1, vector2)

    # Calculate the magnitude of the cross product
    area = 0.5 * np.linalg.norm(cross_product)

    return area

# Example usage
triangle_vertices = np.array([[0, 0], [4, 0], [2, 3]])
triangle_area = calculate_triangle_area(triangle_vertices)
print("Area of the triangle:", triangle_area)

Area of the triangle: 6.0


### **Eigenvector:**

* **An eigenvector is a non-zero vector that, when multiplied by a given matrix, only gets stretched or shrunk but does not change direction.**

* **In other words, if we have a matrix A and a vector v, if multiplying A by v results in a scalar multiple of v, then v is an eigenvector of A.**

* **Note that eigenvectors are stored as columns in the eigenvectors array, so we use .T to transpose it before iterating over the eigenvectors and printing them.**

* **The scalar multiple is called the eigenvalue associated with that eigenvector.**

### **Eigenvalue:**

* **Eigenvalues are the corresponding scalars that tell us how much an eigenvector is stretched or shrunk when it is transformed by a matrix.**

* **Each eigenvector has its eigenvalue. An eigenvalue represents a factor by which the eigenvector is scaled during the transformation.**


**To summarize, an eigenvector is a vector that remains in the same direction (up to a scalar multiple) when multiplied by a matrix, and the corresponding eigenvalue tells us the scale by which that vector is stretched or shrunk.**

###**Demo**

**Question:** **Calculate the eigenvalues and eigenvector for the following array.**

**matrix = ([2, 1], [1, 3])**

In [ ]:
import numpy as np

# Create a matrix
matrix = np.array([[2, 1], [1, 3]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# Print the eigenvalues
print("Eigenvalues:", eigenvalues)

# Print the eigenvectors
print("Eigenvectors:")
for vector in eigenvectors.T:
    print(vector)

Eigenvalues: [1.38196601 3.61803399]
Eigenvectors:
[-0.85065081  0.52573111]
[-0.52573111 -0.85065081]


###**Practice Time**

**Question: 1**

**Calculate the eigenvalues and eigenvector for the following array.**

**A = [(5,6),(9,3)]**

In [ ]:
# Define the matrix A
A = np.array([[5, 6], [9, 3]])

# Calculate the eigenvectors of A
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print the eigenvalues
print("Eigenvalues:", eigenvalues)

print("Eigenvectors:")
for i in range(len(eigenvectors)):
    print(eigenvectors[:,i])


Eigenvalues: [11.41619849 -3.41619849]
Eigenvectors:
[0.68302051 0.73039919]
[-0.58049671  0.81426259]


**Question: 2**

**Calculate the eigenvalues and eigenvector for the following array.**

**Vector = [(1,2),(3,4)]**

In [ ]:
# Create a 2x2 matrix
Vector = np.array([[1, 2], [3, 4]])

# Find the eigenvalues and eigenvectors of A
w, v = np.linalg.eig(A)

# Print the eigenvalues and eigenvectors
print("Eigenvalues:", w)
print("Eigenvectors:", v)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### **Matrices**

**A Python matrix is a specialized two-dimensional rectangular array of data stored in rows and columns.**

**The data in a matrix can be numbers, strings, expressions, symbols, etc.**

**Python provides several ways to perform operations on matrices. Here are some common operations you can perform using various matrices.**

#### **Matrix Creation**

In [ ]:
#Matrix Creation:

import numpy as np

# Create a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Operations in Matrices:
    

**Demo**

**Questions:** **Perform matrix operations of addition and subtraction and multiplication on 2 array consisting of values [1, 2], [3, 4] and [5, 6], [7, 8]**

In [ ]:
#Addition and Subtraction:

import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = matrix1 + matrix2  # Addition
# result = np.add(matrix1, matrix2)
print(result)
# Output: [[6 8]
#          [10 12]]

result = matrix1 - matrix2  # Subtraction
# result = np.subtract(matrix1, matrix2)
print(result)
# Output: [[-4 -4]
#          [-4 -4]]

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [ ]:
# Multiplication and dot product:

import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = matrix1 * matrix2  # Element-wise multiplication
# result = np.multiply(matrix1, matrix2)
print(result)


#DOT PRODUCT
result = np.dot(matrix1, matrix2)  # Matrix multiplication
print(result)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


**Transposition**

In Python, the transpose function is used to interchange the rows and columns of a matrix or a two-dimensional array. It essentially flips the matrix along its diagonal.



**Demo**

**Question: Write a program to create a 2D array with the values [1, 2, 3] and [4, 5, 6], and then transpose the array?**

In [ ]:
#Transposition:

import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])

result = np.transpose(matrix)
print(result)

[[1 4]
 [2 5]
 [3 6]]


**Practice Time**

**Question: Write a program to create a 2D array with the values [7, 7, 3], [2, 9, 6] and [0, 5, 1], and then transpose the array?**

In [ ]:
# Define the matrix A
A = np.array([[7, 7, 3], [2, 9, 6], [0, 5, 1]])

print("Matrix\n", A)
# Calculate the transpose of A using NumPy
A_transpose = np.transpose(A)

print("\nTranspose of A using NumPy:\n", A_transpose)

Matrix
 [[7 7 3]
 [2 9 6]
 [0 5 1]]

Transpose of A using NumPy:
 [[7 2 0]
 [7 9 5]
 [3 6 1]]


#### **Determinant:**

Determinant is a very useful value in linear algebra. It calculated from the diagonal elements of a square matrix. For a 2x2 matrix, it is simply the subtraction of the product of the top left and bottom right element from the product of other two.

In other words, for a matrix [[a,b], [c,d]], the determinant is computed as ‘ad-bc’. The larger square matrices are considered to be a combination of 2x2 matrices.

The numpy.linalg.det() function calculates the determinant of the input matrix.


In [ ]:
#Determinant:

import numpy as np

matrix = np.array([[1, 2], [3, 4]])

result = np.linalg.det(matrix)
print(result)
# Output: -2.0

-2.0000000000000004


In [ ]:
# Define the matrix A
A = np.array([[7, 7, 3], [2, 9, 6], [0, 5, 1]])

# Calculate the determinant of A using NumPy
A_det = np.linalg.det(A)

print("Determinant of A using NumPy:", A_det)


Determinant of A using NumPy: -130.99999999999994


###**inverse:**


We use numpy.linalg.inv() function to calculate the inverse of a matrix. The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix.

In [ ]:

#Inversion:

import numpy as np

matrix = np.array([[1, 2], [3, 4]])

result = np.linalg.inv(matrix)
print(result)
# Output: [[-2.   1. ]
#          [ 1.5 -0.5]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# Define the matrix A
A = np.array([[7, 7, 3], [2, 9, 6], [0, 5, 1]])

# Calculate the inverse of A using NumPy
A_inv = np.linalg.inv(A)

print("Inverse of A using NumPy:\n", A_inv)

Inverse of A using NumPy:
 [[ 0.16030534 -0.0610687  -0.11450382]
 [ 0.01526718 -0.05343511  0.27480916]
 [-0.07633588  0.26717557 -0.3740458 ]]


###**Normalise:**

To normalize a matrix means to scale the values such that that the range of the row or column values is between 0 and 1. The easiest way to normalize the values of a NumPy matrix is to use the normalize() function from the sklearn package, which uses the following basic syntax: from sklearn.

In [ ]:
A = np.array([[1, 2], [3, 4]])

# Calculate the magnitude of the vector
magnitude = np.linalg.norm(A)

# Normalize the vector by dividing each element by the magnitude
normalized_vector = A / magnitude

print(normalized_vector)

[[0.18257419 0.36514837]
 [0.54772256 0.73029674]]


In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])

matrix_norm = np.linalg.norm(A)

print("Matrix norm: ", matrix_norm)


Matrix norm:  9.539392014169456


In [ ]:
# define the matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# calculate the norm of the matrix
norm_A = np.linalg.norm(A)

# normalize the matrix
A_norm = A / norm_A

print("Original matrix:\n", A)
print("Normalized matrix:\n", A_norm)

Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized matrix:
 [[0.05923489 0.11846978 0.17770466]
 [0.23693955 0.29617444 0.35540933]
 [0.41464421 0.4738791  0.53311399]]


In [ ]:
import numpy as np

fruits = np.array([['Mango'],['Orange'],['Apple']])
Price = np.array([[9],[23],[66]])
kg = np.array([[2],[4], [3]])
vegetables = np.array([['Carrot'],['Spinach'],['Broccoli']])
kilogram = np.array([[6], [9], [12]])
price = np.array([[25],[12],[50]])

# Add the fruits and vegetables arrays
Total_cost_fruits = Price*kg

# Print the fruits_vegetables array
print(Total_cost_fruits)

[[ 18]
 [ 92]
 [198]]


In [ ]:
import numpy as np

# Convert the given lists to NumPy arrays
fruits = np.array([[27, 19, 11], [9, 23, 66], [11, 55, 88], [43, 87, 56]])
vegetables = np.array([[32, 12, 44], [6, 9, 12], [37, 29, 51], [17, 13, 19]])

# Addition
result_addition = fruits + vegetables
print("Addition:")
print(result_addition)
# Output:
# [[59 31 55]
#  [15 32 78]
#  [48 84 139]
#  [60 100 75]]



In [ ]:
fruits = np.array([['Mango'],['Orange'],['Apple']])
fruits_Price = np.array([[9],[23],[66]])
kg = np.array([[2],[4], [3]])
vegetables = np.array([['Carrot'],['Spinach'],['Broccoli']])
kilogram = np.array([[6], [9], [12]])
veg_price = np.array([[25],[12],[50]])
discount = np.array([[3],[5],[7]])

# Add the fruits and vegetables arrays
Total_cost_fruits = Price*kg
total_cost_veg = veg_price*kilogram

# Print the fruits_vegetables array
print('total cost for fruits are: ',Total_cost_fruits)

price_after_disc_fruits=Total_cost_fruits-discount
price_after_disc_fruits
print('Price after discount for fruits are: ',price_after_disc_fruits)

print("...............")
print('total cost for vegetables are: ',total_cost_veg)
price_after_disc_veg=total_cost_veg-discount
price_after_disc_veg
print('Price after discount for vegetables are: ',price_after_disc_veg)

Total_amount_paid = price_after_disc_fruits + price_after_disc_veg
print('total amount paid for both fruits and vegetables are: ',Total_amount_paid)

total cost for fruits are:  [[ 18]
 [ 92]
 [198]]
Price after discount for fruits are:  [[ 15]
 [ 87]
 [191]]
...............
total cost for vegetables are:  [[150]
 [108]
 [600]]
Price after discount for vegetables are:  [[147]
 [103]
 [593]]
total amount paid for both fruits and vegetables are:  [[162]
 [190]
 [784]]


**Practice Time**

**Question: Write a program to create a 2 dimnensional array and perform various matrix operations for the following.**

**fruits = ['Mango','Orange','Apple']**

**fruits_Price = [9,23,66]**

**fruits_kg = [2, 4, 3]**

**vegetables = ['Carrot','Spinach','Broccoli']**

**veg_kg = [6, 9, 12]**

**veg_price =[25, 12, 50]**

**discount = [3, 5, 7]**

**Answer the following questions:**

**Question: 1 Calculate the total cost of fruits and vegetables bought by Nicole, by using matrix operations.**

**Question: 2 Write a program that calculates the final cost of fruits and vegetables after deducting the discount from the original cost by using matrix oprations.**

**Question: 3 Find the total amount that Nicole has to pay for both fruits and vegetables before tax.**

**Question: 4 Write a program to determine the total amount Nicole needs to pay by applying a 5% tax rate on fruits and vegetables.**

In [ ]:
import numpy as np

fruits = np.array([['Mango'],['Orange'],['Apple']])
fruits_Price = np.array([[9],[23],[66]])
fruits_kg = np.array([[2],[4], [3]])
vegetables = np.array([['Carrot'],['Spinach'],['Broccoli']])
veg_kg = np.array([[6], [9], [12]])
veg_price = np.array([[25],[12],[50]])
discount = np.array([[3],[5],[7]])

# Calculate the total cost of fruits
total_fruit_cost = np.sum(fruits_Price * kg, axis=1)
print('The total cost of fruits are: ',total_fruit_cost)
# Calculate the total cost of vegetables
total_veg_cost = np.sum(veg_price * kilogram, axis=1)
print('The total cost of fruits are: ', total_veg_cost)


The total cost of fruits are:  [ 18  92 198]
The total cost of fruits are:  [150 108 600]


In [ ]:

# Calculate the total discount
total_discount = np.sum(discount, axis=1)
total_discount
total_price_fruits=total_fruit_cost- total_discount
print('The total price of fruits after discount are: ',total_price_fruits)
total_price_veg=total_veg_cost- total_discount
print('The total price of vegetables after discount are: ',total_price_veg)


The total price of fruits after discount are:  [ 15  87 191]
The total price of vegetables after discount are:  [147 103 593]


In [ ]:

# Calculate the total amount spent
total_amount = total_price_fruits + total_price_veg
print("Total amount for fruits and vegetables before tax is :", total_amount)

Total amount spent: [162 190 784]


In [ ]:
# Calculate the tax on fruits and vegetables
tax = total_amount * 5/100
print('The tax amount is: ',tax)
# Calculate the total amount spent, including tax.
total_amount_with_tax = total_amount + tax

# Print the total amount spent, including tax.
print("Total amount spent, including tax:", total_amount_with_tax)

The tax amount is:  [ 8.1  9.5 39.2]
Total amount spent, including tax: [170.1 199.5 823.2]


**1. Which of the following is the correct way to add two matrices in Python?**
    
   * **a. A + B**
   * **b. A += B**
   * **c. B += A**
   * **d. A.add(B)**
    
**Ans: a.  A + B**
    
**2. What is the product of the matrices A and B in Python, where A is a 2x3 matrix and B is a 3x2 matrix?**
    
   * **a. A * B**
   * **b. A @ B**
   * **c. B @ A**
   * **d. A.dot(B)**
    
**Ans: b. A @ B**
    
**3. What is the transpose of the matrix A in Python, where A is a 3x2 matrix?**
   
   * **a. A.T**
   * **b. A.transpose()**
   * **c. A.trans()**
   * **d. A.swapaxes(0, 1)**

**Ans: a. A.T**   
    
**4. What is the inverse of the matrix A in Python, where A is a 2x2 matrix?**
    
   * **a. A.inv()**
   * **b. A.inverse()**
   * **c. A.solve()**
   * **d. None of the above**

**Ans: a. A.inv()**

**Question:5**

**Imagine you have the monthly sales data of a company for the past year stored as a vector. How can you find the total sales for the year using Python?**

**Total_sales = [10000, 15000, 12000, 18000, 20000, 22000, 19000, 23000, 25000, 21000, 18000, 22000]**

In [ ]:
#alculate the total sales for the year:

import numpy as np

sales_data = np.array([10000, 15000, 12000, 18000, 20000, 22000, 19000, 23000, 25000, 21000, 18000, 22000])
total_sales = np.sum(sales_data)
print(total_sales)

225000


**Question: 6**

**How would you calculate the Body Mass Index (BMI) for each individual in Python, given their heights and weights as arrays? The heights array contains [165, 170, 155, 180, 175] and the weights array contains [60, 65, 50, 75, 70].**

In [ ]:
import numpy as np

heights = np.array([165, 170, 155, 180, 175])
weights = np.array([60, 65, 50, 75, 70])

bmi = weights / ((heights / 100) ** 2)
print(bmi)

[22.03856749 22.49134948 20.81165453 23.14814815 22.85714286]


**Question: 7**

**From the numpy array "temperature_data" containing the values [25, 28, 30, 32, 29, 27, 26, 24, 23, 22, 20, 21], what is the average temperature?**

In [ ]:
import numpy as np

temperature_data = np.array([25, 28, 30, 32, 29, 27, 26, 24, 23, 22, 20, 21])

average_temperature = np.mean(temperature_data)
print(average_temperature)

25.583333333333332


**Question: 8**

**Calculate the Euclidean distance between two 3D points: point1 = [1, 2, 3] and point2 = [4, 5, 6]. What is the distance between them?**

In [ ]:
#Calculate the Euclidean distance between two 3D points:

import numpy as np

point1 = np.array([1, 2, 3])
point2 = np.array([4, 5, 6])

distance = np.linalg.norm(point2 - point1)
print(distance)


5.196152422706632


In [ ]:
#Find the most influential node in a network:

import numpy as np

network_matrix = np.array([
    [0, 1, 0, 1],
    [1, 0, 1, 0],
    [0, 1, 0, 1],
    [1, 0, 1, 0]
])

influential_node = np.argmax(np.sum(network_matrix, axis=1))
print(influential_node)

0


**Question: 9**

**Consider a scenario where you have user ratings for different movies stored as a matrix. The matrix user_ratings represents the ratings given by three users (User 0, User 1, and User 2) to four movies. The ratings range from 1 to 5. Using this information, how can you recommend similar movies to User 0 based on their ratings?**

In [ ]:
#Recommending similar movies based on user ratings:
import numpy as np

user_ratings = np.array([[5, 4, 3, 1],
                         [2, 3, 5, 4],
                         [4, 5, 1, 2]])

# Calculate similarity matrix (cosine similarity)
similarity_matrix = np.dot(user_ratings, user_ratings.T) / (np.linalg.norm(user_ratings, axis=1)[:, None] * np.linalg.norm(user_ratings, axis=1))

# Find similar movies for a given user (e.g., user 0)
similar_movies = np.argsort(similarity_matrix[0])[::-1]
print("Similar movies for user 0:", similar_movies)

Similar movies for user 0: [0 2 1]


**Question: 10**

**How can you access and extract the age, income, and education level of individuals from a dataset represented as a matrix called dataset? Each row in the matrix represents an individual, while the columns correspond to different features (age, income, and education level).**

**Consider the following dataset:**

dataset = np.array([
   **[25, 50000, 12],**
   
   **[30, 60000, 16],**
   
   **[35, 70000, 14],**
    
   **[28, 55000, 15]**
**])**

**Using Python, demonstrate how you can access and extract the individual features (ages, incomes, and educations) from the dataset matrix.**

In [ ]:
#Representing a dataset with multiple features using a matrix:

import numpy as np

dataset = np.array([
    [25, 50000, 12],
    [30, 60000, 16],
    [35, 70000, 14],
    [28, 55000, 15]
])

# Accessing individual features
ages = dataset[:, 0]
incomes = dataset[:, 1]
educations = dataset[:, 2]

print("Ages:", ages)
print("Incomes:", incomes)
print("Educations:", educations)

Ages: [25 30 35 28]
Incomes: [50000 60000 70000 55000]
Educations: [12 16 14 15]
